#!/usr/bin/lua 

package.path = "./modules/?.lua;"..package.path

local mm = require "mm"

local json = require("dkjson")

local Parser = require("parser")
local Ruleset = require("ruleset")




local p = Parser.new()

local parsed = p:parseFile("./ruleset1.json")

local rs = Ruleset.new(parsed)

mm(rs)
