#!/usr/bin/lua 

local mm = require "mm"

local json = require("dkjson")

require("parser")
require("ruleset")

local f = io.open("./ruleset1.json", "rb")
local rs1 = f:read("*all")
f:close()

local data, pos, err = json.decode(rs1, 1, nil)
mm(data)

local p = Parser.new()

local parsed = p:parseRuleSet(data)

local rs = Ruleset.new(parsed)

mm(rs)
