//AUTOGENERATED, do not edit! see ngx_wafflex_commands.rb
static ngx_command_t  wafflex_commands[] = {
    { ngx_string("wafflex_shared_memory_size"),
    NGX_HTTP_MAIN_CONF|NGX_CONF_TAKE1,
    wfx_conf_set_size_slot,
    NGX_HTTP_MAIN_CONF_OFFSET,
    offsetof(wfx_main_conf_t, shm_size),
    NULL } ,

  { ngx_string("wafflex_load_ruleset"),
    NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_CONF_TAKE1|NGX_CONF_TAKE2,
    wfx_conf_load_ruleset,
    NGX_HTTP_MAIN_CONF_OFFSET,
    0,
    NULL } ,

  { ngx_string("wafflex_ruleset"),
    NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF|NGX_CONF_TAKE1|NGX_CONF_TAKE2|NGX_CONF_TAKE3|NGX_CONF_TAKE4|NGX_CONF_TAKE5,
    wfx_conf_ruleset,
    NGX_HTTP_LOC_CONF_OFFSET,
    0,
    NULL } ,

  { ngx_string("wafflex_redis_url"),
    NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF|NGX_CONF_TAKE1,
    ngx_conf_set_redis_url,
    NGX_HTTP_LOC_CONF_OFFSET,
    offsetof(wfx_loc_conf_t, redis.url),
    NULL } ,


  ngx_null_command
};
