// don't edit this please, it was auto-generated by hsss
// https://github.com/slact/hsss

typedef struct {
  char *name;
  char *script;
} wfx_redis_lua_script_t;

typedef struct {
  //lua environs initializer
  wfx_redis_lua_script_t init;

  wfx_redis_lua_script_t ipc;

  wfx_redis_lua_script_t limiter;

  wfx_redis_lua_script_t redis;

  wfx_redis_lua_script_t tag;

  wfx_redis_lua_script_t tracer;

} wfx_redis_lua_scripts_t;
wfx_redis_lua_scripts_t wfx_redis_lua_scripts;
#define WFX_REDIS_LUA_SCRIPTS_EACH(script) \
for((script)=(wfx_redis_lua_script_t *)&wfx_redis_lua_scripts; (script) < (wfx_redis_lua_script_t *)(&wfx_redis_lua_scripts + 1); (script)++) 
